import axios from 'axios';

const API_URL = process.env.REACT_APP_API_URL || 'http://localhost:8080/api';

// Create axios instance with default headers
const api = axios.create({
  baseURL: API_URL,
  headers: {
    'Content-Type': 'application/json',
  }
});

// Add token to requests if it exists
api.interceptors.request.use(
  (config) => {
    const token = localStorage.getItem('token');
    if (token) {
      config.headers.Authorization = `Bearer ${token}`;
    }
    return config;
  },
  (error) => Promise.reject(error)
);

// ============ AUTH ENDPOINTS ============

// Register a new user
export const register = async (name, email, password) => {
  const response = await api.post('/auth/register', { name, email, password });
  return response.data;
};

// Login user
export const login = async (email, password) => {
  const response = await api.post('/auth/login', { email, password });
  if (response.data.data) {
    localStorage.setItem('token', response.data.data.token);
    localStorage.setItem('refreshToken', response.data.data.refreshToken);
    localStorage.setItem('user', JSON.stringify(response.data.data.user));
  }
  return response.data;
};

// Refresh token
export const refreshToken = async () => {
  const refreshToken_token = localStorage.getItem('refreshToken');
  const response = await api.post('/auth/refresh-token', { refreshToken: refreshToken_token });
  if (response.data.data) {
    localStorage.setItem('token', response.data.data.token);
  }
  return response.data;
};

// Logout user
export const logout = () => {
  localStorage.removeItem('token');
  localStorage.removeItem('refreshToken');
  localStorage.removeItem('user');
};

// Get current user from localStorage
export const getCurrentUser = () => {
  const user = localStorage.getItem('user');
  return user ? JSON.parse(user) : null;
};

// Get current user profile from API
export const getProfile = async () => {
  const response = await api.get('/auth/me');
  return response.data;
};

// ============ BOOK ENDPOINTS ============

// Get all books
export const getAllBooks = async (page = 1, limit = 10) => {
  const response = await api.get(`/books/all?page=${page}&limit=${limit}`);
  return response.data;
};

// Get all books (simple)
export const getBooks = async () => {
  const response = await api.get('/books/books');
  return response.data;
};

// Get all users
export const getAllUsers = async () => {
  const response = await api.get('/books/users');
  return response.data;
};

// Search for a book by name
export const searchBooks = async (bookName, page = 1, limit = 10) => {
  const response = await api.get(`/books/search?name=${bookName}&page=${page}&limit=${limit}`);
  return response.data;
};

// Filter books by rent range
export const filterBooksByRent = async (minRent, maxRent) => {
  const response = await api.get(`/books/filter-by-rent?minRent=${minRent}&maxRent=${maxRent}`);
  return response.data;
};

// ============ TRANSACTION ENDPOINTS ============

// Issue a book to a user (requires authentication)
export const issueBook = async (bookName, userName, issueDate) => {
  const response = await api.post('/books/issue-book', {
    bookName,
    userName,
    issueDate,
  });
  return response.data;
};

// Return a book and calculate rent (requires authentication)
export const returnBook = async (bookName, userName, returnDate) => {
  const response = await api.post('/books/return-book', {
    bookName,
    userName,
    returnDate,
  });
  return response.data;
};

// Get total rent generated by a book
export const getTotalRent = async (bookName) => {
  const response = await api.get(`/books/total-rent?bookName=${bookName}`);
  return response.data;
};

// Get all books issued by a specific user
export const getIssuedBooksByUser = async (userName) => {
  const response = await api.get(`/books/issued-books?userName=${userName}`);
  return response.data;
};

// Get users who issued a specific book
// export const getIssuedUsers = async (bookName) => {
//   const response = await api.get(`/books/issued-users?bookName=${bookName}`);
//   return response.data;
// };

// Get books issued within a date range
export const getBooksInDateRange = async (startDate, endDate) => {
  const response = await api.get(`/books/issued-in-date-range?startDate=${startDate}&endDate=${endDate}`);
  return response.data;
};

// Get users who issued a specific book
export const getIssuedUsers = async (bookName) => {
  const response = await api.get(`/books/issued-users?bookName=${encodeURIComponent(bookName)}`);
  return response.data;
};

export default api;
